# Generated by Django 5.2.5 on 2025-08-26 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_creator_kycsession_payout_purchase_stream_reward_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='stream',
        ),
        migrations.AlterUniqueTogether(
            name='streamviewer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='streamviewer',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='streamviewer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gift',
            name='message',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='playback_url',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='stream_url',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='total_gifts',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='viewer_count',
        ),
        migrations.AddField(
            model_name='stream',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stream',
            name='theatre_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gift',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='gift',
            name='gift_type',
            field=models.CharField(default='rose', max_length=50),
        ),
        migrations.AlterField(
            model_name='gift',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stream',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stream',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='KYCSession',
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
        migrations.DeleteModel(
            name='Payout',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
        migrations.DeleteModel(
            name='StreamViewer',
        ),
    ]
