# Generated by Django 5.2.5 on 2025-08-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_creator_user_remove_stream_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='stream_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='viewer_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
