# Generated by Django 5.2.5 on 2025-08-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_populate_transaction_hashes'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='audio_processed_at',
            field=models.DateTimeField(blank=True, help_text='When audio processing was completed', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='audio_quality_score',
            field=models.FloatField(blank=True, help_text='Audio quality score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='transcript',
            field=models.TextField(blank=True, help_text='Auto-generated transcript', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='transcript_language',
            field=models.CharField(blank=True, help_text='Detected language', max_length=10, null=True),
        ),
    ]
