# Generated by Django 5.2.5 on 2025-08-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_comment_sentiment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='video_analysis_error',
            field=models.TextField(blank=True, help_text='Error message if analysis failed', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='video_analysis_processed_at',
            field=models.DateTimeField(blank=True, help_text='When video analysis was completed', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='video_analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of video analysis using Gemini API', max_length=20),
        ),
        migrations.AddField(
            model_name='short',
            name='video_analysis_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of video content', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='video_content_categories',
            field=models.JSONField(blank=True, default=list, help_text='Content categories identified by AI'),
        ),
        migrations.AddField(
            model_name='short',
            name='video_engagement_prediction',
            field=models.FloatField(blank=True, help_text='Predicted engagement score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='video_quality_score',
            field=models.FloatField(blank=True, help_text='Video quality score (0-100) from Gemini analysis', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='video_sentiment_score',
            field=models.FloatField(blank=True, help_text='Content sentiment analysis (-1 to 1)', null=True),
        ),
    ]
