# Generated by Django 5.2.5 on 2025-08-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_short_video_analysis_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='video_content_engagement',
            field=models.FloatField(blank=True, help_text='Content engagement score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='video_content_focus',
            field=models.FloatField(blank=True, help_text='Content focus and clarity score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='video_content_sensitivity',
            field=models.FloatField(blank=True, help_text='Content appropriateness score (0-5)', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='video_demographic_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Demographic-specific analysis data'),
        ),
        migrations.AddField(
            model_name='short',
            name='video_demographic_appeal',
            field=models.FloatField(blank=True, help_text='Demographic appeal score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='video_detailed_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed score breakdown'),
        ),
        migrations.AddField(
            model_name='short',
            name='video_originality',
            field=models.FloatField(blank=True, help_text='Originality and creativity score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='video_overall_score',
            field=models.FloatField(blank=True, help_text='Weighted overall analysis score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='video_technical_quality',
            field=models.FloatField(blank=True, help_text='Technical production quality score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='video_viral_potential',
            field=models.FloatField(blank=True, help_text='Viral potential and shareability score (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='short',
            name='video_engagement_prediction',
            field=models.FloatField(blank=True, help_text='Legacy: Predicted engagement score (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='short',
            name='video_quality_score',
            field=models.FloatField(blank=True, help_text='Legacy: Technical quality score (0-100) from Gemini analysis', null=True),
        ),
    ]
