# Generated by Django 5.2.5 on 2025-08-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_short_video_content_engagement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='ai_bonus_percentage',
            field=models.FloatField(blank=True, help_text='AI bonus percentage from video/audio quality', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='final_reward_score',
            field=models.FloatField(blank=True, help_text='Final calculated reward score', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='main_reward_score',
            field=models.FloatField(blank=True, help_text='Base reward from views, likes, comments', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='moderation_adjustment',
            field=models.FloatField(blank=True, help_text='Moderation adjustment percentage (-10% to +10%)', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='reward_calculated_at',
            field=models.DateTimeField(blank=True, help_text='When reward was last calculated', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('view_reward', 'View Reward'), ('like_reward', 'Like Reward'), ('comment_reward', 'Comment Reward'), ('content_creator_reward', 'Content Creator Reward'), ('ai_bonus', 'AI Quality Bonus'), ('moderation_adjustment', 'Moderation Adjustment'), ('withdrawal', 'Withdrawal'), ('bonus', 'Bonus')], max_length=30),
        ),
    ]
