# Generated by Django 5.2.5 on 2025-08-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_reward_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='ai_bonus_reward',
            field=models.FloatField(blank=True, help_text='AI bonus reward amount in points', null=True),
        ),
    ]
