# Generated by Django 5.2.5 on 2025-08-30 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_ai_bonus_reward_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='is_flagged_for_moderation',
            field=models.BooleanField(default=False, help_text='Automatically flagged when comment score < -0.50'),
        ),
        migrations.AddField(
            model_name='short',
            name='moderated_at',
            field=models.DateTimeField(blank=True, help_text='When moderation was performed', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='moderated_by',
            field=models.ForeignKey(blank=True, help_text='Admin who performed moderation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_shorts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='short',
            name='moderation_reason',
            field=models.TextField(blank=True, help_text='Reason for moderation action', null=True),
        ),
        migrations.AddField(
            model_name='short',
            name='moderation_status',
            field=models.CharField(choices=[('none', 'No Moderation Needed'), ('flagged', 'Flagged for Review'), ('under_review', 'Under Review'), ('moderated', 'Moderated'), ('cleared', 'Cleared')], default='none', help_text='Current moderation status', max_length=20),
        ),
        migrations.AlterField(
            model_name='short',
            name='moderation_adjustment',
            field=models.FloatField(blank=True, help_text='Moderation adjustment percentage (-20% to +20%)', null=True),
        ),
    ]
