# Generated by Django 5.2.5 on 2025-08-30 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_moderation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('view_reward', 'View Reward'), ('like_reward', 'Like Reward'), ('comment_reward', 'Comment Reward'), ('content_creator_reward', 'Content Creator Reward'), ('ai_bonus', 'AI Quality Bonus'), ('moderation_adjustment', 'Moderation Adjustment'), ('monthly_revenue_share', 'Monthly Revenue Share'), ('withdrawal', 'Withdrawal'), ('bonus', 'Bonus')], max_length=30),
        ),
        migrations.CreateModel(
            name='MonthlyPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payout_year', models.PositiveIntegerField()),
                ('payout_month', models.PositiveIntegerField()),
                ('total_points', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_platform_points', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('platform_revenue', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('creator_share_percentage', models.DecimalField(decimal_places=4, default=0.5, max_digits=5)),
                ('earned_amount', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('shorts_count', models.PositiveIntegerField(default=0)),
                ('calculation_details', models.JSONField(blank=True, default=dict, help_text='Detailed breakdown of points calculation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_payout', to='api.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_payouts', to=settings.AUTH_USER_MODEL)),
                ('withdrawal_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawn_payout', to='api.transaction')),
            ],
            options={
                'ordering': ['-payout_year', '-payout_month', '-earned_amount'],
                'indexes': [models.Index(fields=['user', '-payout_year', '-payout_month'], name='api_monthly_user_id_8a2875_idx'), models.Index(fields=['status'], name='api_monthly_status_838a3d_idx'), models.Index(fields=['payout_year', 'payout_month'], name='api_monthly_payout__797cfe_idx')],
                'unique_together': {('user', 'payout_year', 'payout_month')},
            },
        ),
    ]
