# Generated by Django 5.2.5 on 2025-08-30 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_transaction_transaction_type_monthlypayout'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, help_text='Total platform revenue for the month', max_digits=12)),
                ('revenue_sources', models.JSONField(blank=True, default=dict, help_text='Breakdown of revenue sources')),
                ('creator_share_percentage', models.DecimalField(decimal_places=2, default=50.0, help_text='Percentage going to creators', max_digits=5)),
                ('creator_pool', models.DecimalField(decimal_places=2, default=0, help_text='Amount allocated to creators', max_digits=12)),
                ('platform_keeps', models.DecimalField(decimal_places=2, default=0, help_text='Amount platform keeps', max_digits=12)),
                ('is_finalized', models.BooleanField(default=False, help_text='Revenue finalized for payout processing')),
                ('payouts_processed', models.BooleanField(default=False, help_text='Payouts have been processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text="Admin notes about this month's revenue")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_revenues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['year', 'month'], name='api_platfor_year_9d3a0f_idx'), models.Index(fields=['is_finalized'], name='api_platfor_is_fina_db5575_idx'), models.Index(fields=['payouts_processed'], name='api_platfor_payouts_77ca28_idx')],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
