# Generated by Django 5.2.5 on 2025-08-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_platformrevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached count of comments'),
        ),
        migrations.AddField(
            model_name='short',
            name='like_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached count of likes'),
        ),
    ]
