# Generated by Django 5.2.5 on 2025-09-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_short_comment_count_short_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='average_watch_percentage',
            field=models.FloatField(default=0.0, help_text='Average watch percentage (0-100)'),
        ),
    ]
